version: '3.9'

services:
  postgres:
    image: 'postgres:16.1'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=develop
    ports:
      - '5432:5432'
    volumes:
      - './data/postgres:/var/lib/pgsql/data'